dnz145/dnz145/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    
]


if settings.DEBUG:
    urlpatterns += static( settings.STATIC_URL, document_root = settings.STATIC_ROOT )
    urlpatterns += static( settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    

dnz145/posts/urls.py
from django.urls import path

from .views import HomePageView, PostPaginationView, DetailPostView

app_name = 'post'

urlpatterns = [
    path('', HomePageView.as_view(), name='home_page'),
    path('posts/<slug:slug>/', PostPaginationView.as_view(), name='posts'),
    path('posts/<slug:slug_topic>/detail/<slug:slug_post>/', DetailPostView.as_view(), name='post_detail'),
]

dnz145/posts/models.py
import uuid
import os

from django.db import models
from django.conf import settings
from django.dispatch import receiver
from ckeditor_uploader.fields import RichTextUploadingField

def get_file_path(instance, filename):
    ext = filename.split('.')[-1]
    filename = f"dnz145-{uuid.uuid4()}.{ext}"
    return f'upload_file/{filename}'
    
class Topic(models.Model):
    class Meta:
        db_table = 'topics' 
        ordering = ('name',)
        verbose_name = 'назви тем'
        verbose_name_plural = 'назви тем'

    name = models.CharField(max_length=2000, help_text='Назва теми', verbose_name='Назва теми') 
    active = models.BooleanField(default=True, help_text='Чи активна ця тема на сайті', verbose_name='Активація')
    slug = models.SlugField(null=False, blank=False, unique=True, help_text='Чипати у виподку інформування', verbose_name='Слаг')

    def __str__(self,):
        return self.name


class Post(models.Model):
    class Meta:
        db_table = 'posts'
        ordering = ('last_update',)
        verbose_name = 'Пости'
        verbose_name_plural = 'Пости'

    topic = models.ForeignKey(Topic, null=False, blank=False, related_name='posts', on_delete=models.CASCADE,
                                help_text='Тема посту', verbose_name='Оберіть тему посту к якій відносится пост')
    name = models.CharField(max_length=2000, null=True, blank=True, unique=False, 
                                    help_text='Впішить назву даного посту', verbose_name='Назва поста')
    text = RichTextUploadingField(verbose_name='Текс для посту', 
                        help_text='Відкерактуйте текст, так Ви бажаєте щоб він виглядав на сайті')
    last_update = models.DateTimeField(auto_now=True, verbose_name='Част останнього редагування')
    slug = models.SlugField(null=False, blank=False, unique=True, help_text='Чипати у виподку інформування', verbose_name='Слаг')
    active = models.BooleanField(default=True,help_text='Чи активна цей пост на сайті', verbose_name='Активація')

    def __str__(self,):
        return self.name

class File(models.Model):
    class Meta:
        db_table = 'files'
        ordering = ('id',)
        verbose_name = 'Файли'
        verbose_name_plural = 'Файли'
    
    name = models.CharField(max_length=2000, null=True, blank=True, default='Файл',
                            help_text='Назва файла не обов\'язкова', verbose_name='Назва файла')
    file_link = models.FileField(upload_to=get_file_path, help_text='Оберіть потрібний файл для поста', verbose_name='Загрузити файл')
    post = models.ForeignKey(Post, null=False, blank=False, on_delete=models.CASCADE, related_name='files', 
                                help_text='До якого посту приєднати файл', verbose_name='Пост')
    active = models.BooleanField(default=True, help_text='Чи активна цей файл на сайті', verbose_name='Активація')

    def __str__(self):
        return self.name if self.name is not None else 'Фаил'


# These two auto-delete files from filesystem when they are unneeded:

@receiver(models.signals.post_delete, sender=File)
def auto_delete_file_on_delete(sender, instance, **kwargs):
    """
    Deletes file from filesystem
    when corresponding `MediaFile` object is deleted.
    """
    if instance.file_link:
        if os.path.isfile(instance.file_link.path):
            os.remove(instance.file_link.path)

@receiver(models.signals.pre_save, sender=File)
def auto_delete_file_on_change(sender, instance, **kwargs):
    """
    Deletes old file from filesystem
    when corresponding `MediaFile` object is updated
    with new file.
    """
    if not instance.pk:
        return False

    try:
        old_file = File.objects.get(pk=instance.pk).file_link
    except File.DoesNotExist:
        return False

    new_file = instance.file_link
    if not old_file == new_file:
        if os.path.isfile(old_file.path):
            os.remove(old_file.path)

dnz145/posts/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.views.generic import TemplateView
from django.views.generic import ListView
from django.views.generic import DetailView

from .models import Topic, Post, File

class HomePageView(TemplateView):
    template_name='home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['topics'] = Topic.objects.filter(active=True).order_by('id').values('name', 'slug')
        return context


class PostPaginationView(ListView):
    template_name = 'pagination_posts.html'
    paginate_by = 30
    model = Post
    context_object_name = 'posts_list'

    def get_queryset(self):
        return self.model.objects.filter(active=True, topic__slug=self.kwargs['slug'])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['active_topic'] = self.kwargs['slug']
        topic =  Topic.objects.filter(active=True, slug=self.kwargs['slug']).values_list('name', flat=True)
        if topic:
            context['topic'] = topic[0]
        context['topics'] = Topic.objects.filter(active=True).order_by('id').values('name', 'slug')
        print(context)
        return context

class DetailPostView(DetailView):
    model = Post 
    queryset = Post.objects.filter(active=True)
    context_object_name = 'post'
    template_name = 'post_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['active_topic'] = self.kwargs['slug_topic']
        context['topics'] = Topic.objects.filter(active=True).order_by('id').values('name', 'slug')
        return context

    def get_object(self, **kwargs):
        return self.queryset.filter(slug=self.kwargs['slug_post']).first()

dnz145/posts/templates/home.html
{% extends 'base.html' %}


{% block title %}
    {{ block.super }} Головна
{% endblock %}

{% block content %}
  <div>
    <p class="text-center h3 m-3">РАДІ ВІТАТИ ВАС НА САЙТІ НАШОГО ЗАКЛАДУ ДОШКІЛЬНОЇ ОСВІТИ!</p>
    <p class="text-justify font-weight-bold m-1">На сайті Ви знайдете інформацію про наш заклад освіти, про
      вихователів та спеціалістів, які працюють в закладі, про все те нове та
      цікаве, що відбувається в нашому закладі.</p>

    <p class="text-justify m-1"> Заклад дошкільної освіти (ясла-садок) комбінованого типу № 145
      &quot;Дружна сімейка&quot; Запорізької міської ради для дітей віком від одного до
      шести (семи) років (для дітей з особливими освітніми потребами - від одного
      до семи (восьми) років), у складі якого можуть бути утворені групи
      загального розвитку, компенсуючого типу (спеціальні групи для дітей з
      порушеннями мовлення; санаторні групи для дітей з ранніми проявами
      туберкульозної інфекції), інклюзивні, сімейні, прогулянкові, в яких
      забезпечується дошкільна освіта відповідно до вимог Базового компонента
      дошкільної освіти та з урахуванням стану здоров’я дітей, їх розумового,
      психологічного, фізичного розвитку.</p>
  </div>
  <div class="row mt-3">
    <div class="col-12 col-xl-3">
      <p class="">Адреса: 69005, м. Запоріжжя, бульвар Центральний, 16А</p>
      <p class="">Телефон: (061) 226-51-46,226-52-32</p>
      <p class="">E-mail: dnz_145@ ukr.net</p>
      <p class="">Режим роботи: понеділок - п&#39;ятниця. 06.30 - 18.30</p>

      <p class="">Директор Шелемаха Алла Анатоліївна</p>
      <p class="">ЧАСИ ПРИЙОМУ:<br/>понеділок 07.00 - 11.00<br/>середа 15.30 - 17.30</p>
    </div>
    <div class="col-12 col-xl-8 offset-xl-1">
      <iframe width="412" height="400" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" id="gmap_canvas" src="https://maps.google.com/maps?width=412&amp;height=400&amp;hl=en&amp;q=%D0%91%D1%83%D0%BB%D1%8C%D0%B2%D0%B0%D1%80%20%D0%A6%D0%B5%D0%BD%D1%82%D1%80%D0%B0%D0%BB%D1%8C%D0%BD%D0%B8%D0%B9%2016%D0%90%20%D0%97%D0%B0%D0%BF%D0%BE%D1%80%D0%BE%D0%B6%D1%8C%D0%B5+(%D0%94%D0%94%D0%A3%20%E2%84%96145%20%D0%94%D0%A0%D0%A3%D0%96%D0%9D%D0%90%D0%AF%20%D0%A1%D0%95%D0%9C%D0%AC%D0%AF)&amp;t=&amp;z=12&amp;ie=UTF8&amp;iwloc=B&amp;output=embed"></iframe> <a href='http://maps-generator.com/ru'>maps-generator.com</a> <script type='text/javascript' src='https://embedmaps.com/google-maps-authorization/script.js?id=4b872a3d7bbe144dca94d4eb9e2a0c0cdfcee202'></script>
    </div>
  </div>
  
  <div>
    <p class="text-center h3 m-3">Електронна реєстрація в ЗДО</p>
    <p class="text-center m-3">Шановні батьки!</p>
    <p class="text-justify m-1"> Ви маєте можливість зареєструвати Вашу дитину до нашого ЗДО через
      мережу Інтернет.
      Для подачі заявки на реєстрацію Вам необхідно зареєструватися на сайті
      https://reg.isuo.org/preschools
      Після внесення всіх необхідних даних Ви можете стежити за перебігом
      електронної черги.</p>
  </div>

  <div>
    <p class="text-center h3 m-3">В нашому закладі використовують такі інструменти спілкування при дистанційному навчанні:</p>
    <ul>
      <li>Сайт ЗДО - некомерційний інтернет-ресурс, який призначений для
представлення інтересів закладу у глобальній мережі, отримання доступу
користувачів інтернету до інформаційних ресурсів, розвитку зв&#39;язків з
іншими організаціями, встановлення персональних контактів, а також для
отримання оперативної інформації всіма учасниками освітнього процесу.
Сайт є одним із інструментів забезпечення освітньої, просвітницької
діяльності ЗДО і є публічним органом інформації, доступ до якої відкритий
для всіх бажаючих;</li>
<li>Електронна пошта - це стандартний сервіс Інтернету, що забезпечує
передавання повідомлень;</li>
<li>Відеоконференція - це конференція реального часу в on-line режимі. Вона
проводиться у визначений день і в призначений час. Відеоконференція - один
із сучасних способів зв&#39;язку, що дозволяє проводити спілкування у
«віддалених групах». Отже, обговорення відбувається у режимі реального
часу. Педагог і діти та їх батьки можуть бачити один одного. Ми
використовуємо програму Zoom для організації відеоконференцій,
розроблену компанією Zoom Video Communication та Google Meet - це сервіс,
де можна проводити високоякісні й безпечні відеозустрічі та дзвінки, він
доступний для всіх користувачів і пристроїв;</li>
<li>Соціальна мережа Facebook, яка дозволяє створювати закриті та відкриті
канали, групи, чати, обговорення тем, завдань, проблем, інформації;</li>
<li>В кожній віковій групі створено групу з батьками в
мережі Viber або Telegram для надання рекомендацій щодо здійснення
освітньої роботи за окремими темами (фото-, аудіо-, відео-, письмово тощо)
та отримання фотозвітів (за бажанням батьків).</li>
    </ul>
  </div>

{% endblock %}

dnz145/posts/templates/pagination_posts.html
{% extends 'base.html' %}

{% block title %}
    {{ block.super }} {{ topic }}
{% endblock %}

{% block style %}
    {{ block.super }} 

    <style>
        .custom-link {
            color: rgba(36, 142, 166,1);
        }

        .custom-link:hover {
            color: rgba(36, 142, 166, 0.7);
        }

        .post-row{
            background-color: rgba(255, 255, 255, 0.1) ;
        }
    </style>
{% endblock %}

{% block content %}

    <p class="h3 my-3 text-center">{{topic}}</p>
    
    <ul class="list-group list-group-flush ">
        {% for post in posts_list %}
        <li class="list-group-item row post-row"><span >  {{post.name}}</span>  <a href="{% url 'post:post_detail' active_topic post.slug %}" class="btn btn-link float-right custom-link">Детальніше</a></li>
        {% endfor %}
      </ul>

    {% if is_paginated %} 
    <ul class="pagination">
    {% if page_obj.has_previous %}
        <li>
            <span><a href="?page={{ page_obj.previous_page_number }}">Попередня</a></span>
        </li>
    {% endif %}
        <li class="">
            <span>Сторінка {{ page_obj.number }} із {{ page_obj.paginator.num_pages }}.</span>
        </li>
    {% if page_obj.has_next %}
        <li>
            <span><a href="?page={{ page_obj.next_page_number }}">Наступна</a></span>
        </li>
    {% endif %}
    </ul>

    {% endif %}

{% endblock %}

dnz145/posts/templates/post_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    {{ block.super }} {{ post.name }}
{% endblock %}

{% block style %}
    {{ block.super }}
    <style>
        .img-file{
            width: 30px;
            height: 30px;
            margin: 0 auto;
        }

        .file-link{
            display: flex;
            display: -webkit-flex; 
            -webkit-flex-direction: row-reverse;
            flex-direction: column;
            min-width: 5%;
            max-width: 10%;
            margin-left: 2%;
            text-align: center;
        }

        .file-container{
            display: flex;
            flex-direction: row;
        }
    </style>
{% endblock %}

{% block content %}
    <p class="text-center h3 m-3">{{ post.name }} </p>
    <div class="m-3">{{ post.text | safe }} </div>
    <div class="m-3 file-container">
        {% for file in post.files.all %}
            {% if file.active %}
                <a href="{{ file.file_link.url }}" target="_blank" class="file-link">
                    <img src="{% static 'file.jpg' %}" alt="File" class="img-file">
                    <span>{{ file.name }}</span>
                </a>
            {% endif %}
        {% endfor %}
    </div>
{% endblock %}

dnz145/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=1000px">
    <title>ДНЗ №145 | {% block title %} {% endblock %}</title>
    {% load static %}
    <link rel="shortcut icon" href="{% static 'logo_title.png' %}" />


    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
        integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    {% block style %}

    <!--
         background: rgb(36,142,166);
            background: linear-gradient(90deg, rgba(36,142,166,1) 0%, rgba(37,199,217,0.2881720430107527) 35%) no-repeat center center fixed;
    -->
    <style>
        body {
            resize: none;
            min-width: 1009px;
            max-width: 100%;
            background: rgba(37,199,217,0.15);
            -webkit-background-size: cover;
            -moz-background-size: cover;
            -o-background-size: cover;
            background-size: cover;
        }

        .nav {
            border: 2px solid rgba(36,142,166, 0.9);
            border-radius: .55rem;
            background-color: rgba(255,255,255, 0.7);
        }

        .content {
            border-radius: .25rem;
            background-color: rgba(255, 255, 255, 0.7);
        }

        .list-group-custom {
            background-color: rgba(37, 199, 217);
        }

        .list-group-custom:hover {
            background-color: rgba(37, 199, 217, 0.5);
        }

        .active-custom {
            background-color: rgba(36, 142, 166,1) !important;
            border-color: rgba(36, 142, 166,1) !important;
        }
    </style>
    {% endblock %}
</head>

<body>
    <div class="container nav my-2">
        <div class="col-3 offset-1 mt-3 mb-3">
            <img src="{% static 'logo.png' %}" class="rounded mx-auto d-block" style="width: 100%" logo">
        </div>
        <div class="col-6 offset-2 mt-5">
            <p style=" font-size: 20px; ">
                ЗАКЛАД ДОШКІЛЬНОЇ ОСВІТИ (ЯСЛА-САДОК)<br/>
                КОМБІНОВАНОГО ТИПУ № 145 &quot;ДРУЖНА СІМЕЙКА&quot;<br/>
                ЗАПОРІЗЬКОЇ МІСЬКОЇ РАДИ<br/>
            </p>

        </div>
    </div>

    <div class="container   mb-4">
        <div class="row">
            <div class="list-group col-3">
                <a href="{% url 'post:home_page' %}"
                    class="list-group-item list-group-item-action list-group-custom {% if request.resolver_match.url_name == 'home_page' %} active active-custom {% endif %} ">Головна</a>
                {% for topic in topics %}
                <a href="{% url 'post:posts' topic.slug %}"
                    class="list-group-item list-group-item-action list-group-custom {% if active_topic == topic.slug %} active active-custom {% endif %}">{{topic.name}}</a>
                {% endfor %} 
            </div>
            <div class="col-9 content pb-5">

                {% block content %}

                {% endblock %}
            </div>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
        integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
        crossorigin="anonymous"></script>
    {% block script %}
    {% endblock %}
</body>

</html>